name: Terraform
on: [push]
jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3
    - uses: hashicorp/setup-terraform@v2

    - name: Terraform fmt
      id: fmt
      run: terraform fmt -check -diff
      continue-on-error: false

    - name: Terraform Init
      id: init
      run: terraform init

    - name: Set up Go 1.20
      uses: actions/setup-go@v4
      with:
        go-version: "1.20"
      id: go

    - name: Build zip files
      run: |
        make build

    - name: Terraform Validate
      id: validate
      run: terraform validate